
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
# 9183

class Euler29

	@min
	@a_max
	@b_max

	def initialize(a=100,b=100,min=2)
		@a_max = a
		@b_max = b
		@min = 2
	end
	
	
	def solve
		values = Array.new
		2.upto(@a_max) do |a|
			2.upto(@b_max) do |b|
				values.push( a**b )
			end
		end
		values.sort!
		values.uniq!
		values.size
	end
end
